### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by NoName9969** [hypersmc/HackerGuardian#6]
(Sorry , i don`t have a free time )

Cosole :
hackerguardian
[WARNING] Unexpected exception while parsing console command "hackerguardian"
org.bukkit.command.CommandException: Cannot execute command 'hackerguardian' in plugin HackerGuardian v0.1.1 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:746) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:426) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:395) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at java.lang.Thread.run(Unknown Source) [?:?]

player ingame:
[INFO] _No_Name_ issued server command: /hackerguardian

[ERROR] null
org.bukkit.command.CommandException: Cannot execute command 'hackerguardian' in plugin HackerGuardian v0.1.1 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1936) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1779) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1732) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
at java.lang.Thread.run(Unknown Source) [?:?]

/pl : https://imgur.com/nwEnUT8

**Comment by hypersmc** [comment]
Hi!

For me to figure out the issue I also need the startup logs of the plugin.
This error is most likely result of plugin shutting down after no database was supplied.

**Comment by NoName9969** [comment]
[INFO] [HackerGuardian] Enabling HackerGuardian v0.1.1

[INFO] $$$$\ $$\ $$\ $$\ $$$$$$\ $$\ $$\ $$$$\

[INFO] $$ _|$$ | $$ | $$ | $$ __$$\ $$ |\__| \_$$ |

[INFO] $$ | $$ | $$ | $$$$$$\ $$$$$$$\ $$ | $$\ $$$$$$\ $$$$$$\ $$ / \__|$$\ $$\ $$$$$$\ $$$$$$\ $$$$$$$ |$$\ $$$$$$\ $$$$$$$\ $$ |

[INFO] $$ | $$$$$$$$ | \____$$\ $$ _____|$$ | $$ |$$ __$$\ $$ __$$\ $$ |$$$$\ $$ | $$ | \____$$\ $$ __$$\ $$ __$$ |$$ | \____$$\ $$ __$$\ $$ |

[INFO] $$ | $$ __$$ | $$$$$$$ |$$ / $$$$$$ / $$$$$$$$ |$$ | \__|$$ |\_$$ |$$ | $$ | $$$$$$$ |$$ | \__|$$ / $$ |$$ | $$$$$$$ |$$ | $$ | $$ |

[INFO] $$ | $$ | $$ |$$ __$$ |$$ | $$ _$$< $$ ____|$$ | $$ | $$ |$$ | $$ |$$ __$$ |$$ | $$ | $$ |$$ |$$ __$$ |$$ | $$ | $$ |

[INFO] $$$$\ $$ | $$ |\$$$$$$$ |\$$$$$$$\ $$ | \$$\ \$$$$$$$\ $$ | \$$$$$$ |\$$$$$$ |\$$$$$$$ |$$ | \$$$$$$$ |$$ |\$$$$$$$ |$$ | $$ |$$$$ |

[INFO] \____|\__| \__| \_______| \_______|\__| \__| \_______|\__| \______/ \______/ \_______|\__| \_______|\__| \_______|\__| \__|\____|

[INFO] [HackerGuardian] Registering Commands

[INFO] [HackerGuardian] Registering Timers

[INFO] [HackerGuardian] Registering checks

[INFO] [HackerGuardian] No files in: 'category'

[INFO] [HackerGuardian]

[INFO] [HackerGuardian] ---------- Core MySQL ----------

[INFO] [HackerGuardian] Please setup MySQL in the config. When done reboot the server.

[INFO] [HackerGuardian] Disabling plugin. Please reboot to reload config.

[INFO] [HackerGuardian] -----------------------------

[INFO] [HackerGuardian]

[INFO] [HackerGuardian] Disabling HackerGuardian v0.1.1

[ERROR] Error occurred while enabling HackerGuardian v0.1.1 (Is it up to date?)

java.lang.IllegalStateException: zip file closed

at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:?]

at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:?]

at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:?]

at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

at me.hackerguardian.main.Core.onEnable(Core.java:168) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]

at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by hypersmc** [comment]
You need to configure it to connect to a database (preferably MySQL) to use HackerGuardian. It's said in on the spigotmc website. Closing issue.
